language: python
dist: xenial
cache: pip
python:
  - '3.6'
  - '3.7'
  - '3.8'

install:

  - pip install pip lxml scour dummy_wx --upgrade
  - pip install -r requirements.txt
  - pip install tox tox-travis


script:
  - tox


stages:
  - test
  - deploy_pypi

jobs:
  include:
    - stage: deploy_pypi
      python: "3.6"
      script:
        - tox -e icons -e build 1> /dev/null
      deploy:
        on:
          tags: true
          repo: domdfcoding/custom_wx_icons_hicolor
        provider: pypi
        user: "DomDF"
        password:
          secure: lG+Db9/FSrEXDwIOwWMLF3J1ByjHUwFbAfk3wVzfmTzmZ5aGLH79mA32iSbyE5bK99KFbkA9PQTIlQwI4qZnNonbJ/pLoDJYtXxs8NEGeMkn9RH16+YbEquSOTPSopFhGdpMklXTjwmtygUHCgRzvRedk80a48WKgEAyTI9lVOTwKmZiBegaHuLA2Jeq5OKn1TrAj+sKxhQtxy9LLEBi8SmNyx9jpCLhhxWBTNVCyTB0LqzIVp2pfqEakE8gDOS3CZ77z9LxLE/MLzEyl89CSZGh0qAZMG6dl27ZnND0SMLblHv2TP+864wUgLmqWka1fwNm7EIDfwOn+rcJJw8YnuD5xNk+BxouxerzikbRMyE3lsIauUXcj8BM5gTS6paDWraBUBE6C7Mg6ggAUcw6xQFKcq19Z0UPw0Iggcw/2MDsR3ueoA5NW2JGVUjik85FiY48vDB8gTiHVxchj8FkMA5ZcjQf4QZfXLZsZ4vqDwvHq8L0RjB8BRd8LXPAQvp6nEWjTd8TQKzMe7Akga2mkhyRiuN8a1lLxQROGDWK0RpsK7RDuoLk7D5nFrJLvoWNlHH8nTjXa2P6HuzgW/EXon2ar4LRE7Vnb2nWnbiRU3X2UmVtUicXOzW6PJpWF4yeaEszYOduWSgs9V1GkqKouHm0k6S3mNPJi9RnOluCQ+I=
        distributions: "sdist bdist_wheel"
        skip_existing: true
